version: "3.8"
services:
  backend:
    build: ./backend
    container_name: polibus-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
    networks:
      - polibus-network

  web:
    build: ./frontend/web
    container_name: polibus-web
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://polibus-backend:8080"
    networks:
      - polibus-network

networks:
  polibus-network:
    driver: bridge