name: Deploy to Railway

on:
  push:
    branches:
      - main  # Cambia "main" por la rama de despliegue deseada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'  # Asegúrate de usar la versión correcta que tu proyecto necesita

      - name: Build backend project
        run: mvn -f backend/pom.xml clean package  # Compila el proyecto Maven y genera el JAR

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/polibus-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/polibus-backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/polibus-web:latest ./frontend/web
          docker push ${{ secrets.DOCKER_USERNAME }}/polibus-web:latest

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up
